### ISSUE TITLE
email name/picture possibly (?) confusing

### ISSUE THREAD

**Issue by ajschumacher** [aliyarahman/fellowship_application_full#11]
this is from the email confirmation I got, displayed in gmail:

![screen shot 2015-01-15 at 7 04 39 pm](https://cloud.githubusercontent.com/assets/1071322/5769431/71aaf400-9ce9-11e4-8aa3-b2df967734c8.png)

`Aliya === Code for Progress` is essentially my understanding too, but the email address is `aliya@codeforprogress.org` - would it be better to have the email name and the display name aligned?

Very glad to see that unicode is coming through nicely though! :smile:

**Comment by aliyarahman** [comment]
I agree, fixed (:
