### ISSUE TITLE
After submitting "final submission" the IntegrityError at /finalsubmission/ showed up..

### ISSUE THREAD

**Issue by vicesw** [aliyarahman/fellowship_application_full#19]
![screenshot from 2015-01-15 20 23 56](https://cloud.githubusercontent.com/assets/10554558/5770165/8e90010e-9cf4-11e4-8c78-c42264a0e7c7.png)

**Comment by aliyarahman** [comment]
I haven't been able to recreate this error, so if you can make it happen again please comment here!
