### ISSUE TITLE
can't save recommenders unless they're all filled out

### ISSUE THREAD

**Issue by rshorey** [aliyarahman/fellowship_application_full#22]
tried filling out just 1 recommender, it keeps returning to the recommenders page, and if I hit cancel gets rid of the info I entered.

firefox; ubuntu

(everything so far looks good on ff/ubuntu)

**Comment by aliyarahman** [comment]
OHHHHH. I know why. I added validation to not allow submission of two recommenders with the same email address. It's counting two blanks as equal. On it. Thank you!
