### ISSUE TITLE
First/Last name to create an account  VS to fill the application

### ISSUE THREAD

**Issue by rabella** [aliyarahman/fellowship_application_full#26]
I created the account Ricardito, with the email  ricardo-abella@hotmail.com. Then, when I worked on the first section of the application, the system brought my First and Last Names from the account I had created. However, for the test, I changed those first and last names on the application (to Peter CHANGED and Ericson CHANGED -the system accepted that.  Maybe you don't want that happen.

**Comment by aliyarahman** [comment]
Hey Ricardo,

Just clarifying to make sure I understand - are you saying that the first names from a different account appeared in the Profile section's fields?
