### ISSUE TITLE
System crashed when I submitted.

### ISSUE THREAD

**Issue by rabella** [aliyarahman/fellowship_application_full#29]
I created an account using  ricardo-abella@hotmail.com,  I filled out the form -four sections on green. Submitted. System asked: "Ready to submit this application?" Clicked on "Confirm >>", and got this error message: 

DataError at /finalsubmission/
value too long for type character varying(30)
Request Method:	POST
Request URL:	http://apply.codeforprogress.org/finalsubmission/
Django Version:	1.6.5
Exception Type:	DataError
Exception Value:	
value too long for type character varying(30)
Exception Location:	/usr/lib/python2.6/site-packages/django/db/backends/util.py in execute, line 53
Python Executable:	/usr/bin/python
Python Version:	2.6.6
Python Path:	
['/usr/lib64/python26.zip',
 '/usr/lib64/python2.6',
 '/usr/lib64/python2.6/plat-linux2',
 '/usr/lib64/python2.6/lib-tk',
 '/usr/lib64/python2.6/lib-old',
 '/usr/lib64/python2.6/lib-dynload',
 '/usr/lib64/python2.6/site-packages',
 '/usr/lib/python2.6/site-packages',
 '/usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info',
 '/var/www/html/fellowship_application_full/']
Server time:	Tue, 20 Jan 2015 02:19:11 +0000

Then, I went back to find the error. System allowed me to go to  "Your Application Dashboard."  I was able to see and edit or replace the first and second recommenders. But not the THIRD ONE.

**Comment by aliyarahman** [comment]
This is VERY helpful - just found the problem. Thank you!
